version: '3.8'

services:
  frontend:
    build: ./path/to/frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./path/to/backend
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: projetFormation
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
